### ISSUE TITLE
Keep getting Server error! in the login page.

### ISSUE THREAD

**Issue by Xichen96** [tacacsgui/tacacsgui#122]
**Describe the system**
Ubuntu version: ... 
The Ubuntu Server 20.04 LTS on Azure.
(use next command: lsb_release -a )
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
PHP version: ... 
(use next command: php -v )
PHP 7.3.33-9+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Jan  6 2023 16:05:17) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.33, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.33-9+ubuntu20.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
TacacsGUI API version: **IMPORTANT** 
(use next command: php -r 'include "/opt/tacacsgui/web/api/constants.php"; echo APIVER . "\n";' )
0.9.83
Browser: [e.g. chrome, safari]
chrome

**Describe the bug**
First of all, I have to remove lwresd package from script because it is not found. Then everything runs smoothly.
Used tacgui/tacgui to login, keep getting Server error! 500. Would be really great if you could tell me what happened.

**To Reproduce**
3. See error

**Screenshots**
If you have screenshots to help explain your problem, feel free and attach them.
![image](https://user-images.githubusercontent.com/30065554/211878489-b93ebce0-a81b-49a1-a192-fdcc6ab06d23.png)
Feel free to check page. I will keep the server running.

**Additional context**

**Comment by Xichen96** [comment]
Also I tried the password reset tool and got this.

azureuser@test:/opt/tacacsgui/web/api$ php tgui_passwd_reset.php

####################################
Wellcome to password restoring tool!
####################################

Enter Username: tacgui
PHP Fatal error:  Uncaught PDOException: PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in /opt/tacacsgui/web/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:40
Stack trace:
#0 /opt/tacacsgui/web/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(40): PDO->__construct('mysql:host=loca...', 'tgui_user', '69I3o_yjONQG|yB...', Array)
#1 /opt/tacacsgui/web/api/vendor/illuminate/database/Connectors/Connector.php(67): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'tgui_user', '69I3o_yjONQG|yB...', Array)
#2 /opt/tacacsgui/web/api/vendor/illuminate/database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'tgui_user', '69I3o_yjONQG|yB...', Array)
#3 /opt/tacacsgui/web/api/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#4 /opt/tacacsgui/web/a in /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php on line 664

**Comment by Xichen96** [comment]
@gurkin33 Really appreciate if you could help me out. Has been stuck here for quite a while.

**Comment by akaars** [comment]
Same for me and can't find any hint... :(
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

**Comment by akaars** [comment]
The workaround was found here:
https://github.com/tacacsgui/tacacsgui/issues/125
@Xichen96 FYI :)
