### ISSUE TITLE
Server error! 500

### ISSUE THREAD

**Issue by pablosantosubt** [tacacsgui/tacacsgui#138]
Ubuntu version:   Ubuntu 20.04.6 LTS
PHP version: PHP 7.3.33-14+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Sep  2 2023 08:02:05) ( NTS )
TacacsGUI API version: 0.9.83
Browser: [Chrome]

Slim Application Error
The application could not run because of the following error:**

Details
Type: Illuminate\Database\QueryException
Code: 1045
Message: SQLSTATE[HY000] [1045] Access denied for user 'tgui_user'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = tgui and table_name = mavis_local and table_type = 'BASE TABLE')
File: /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php
Line: 664
Trace
#0 /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#1 /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php(333): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#2 /opt/tacacsgui/web/api/vendor/illuminate/database/Schema/MySqlBuilder.php(18): Illuminate\Database\Connection->select('select * from i...', Array)
#3 /opt/tacacsgui/web/api/app/Controllers/Auth/AuthController.php(26): Illuminate\Database\Schema\MySqlBuilder->hasTable('mavis_local')
#4 [internal function]: tgui\Controllers\Auth\AuthController->getSignIn(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#7 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 /opt/tacacsgui/web/api/app/Middleware/ChangeHeaderMiddleware.php(14): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 [internal function]: tgui\Middleware\ChangeHeaderMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#12 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(tgui\Middleware\ChangeHeaderMiddleware), Array)
#13 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#14 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#15 /opt/tacacsgui/web/api/vendor/tuupola/callable-handler/src/CallableHandler.php(51): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /opt/tacacsgui/web/api/vendor/tuupola/slim-jwt-auth/src/JwtAuthentication.php(161): Tuupola\Middleware\CallableHandler->handle(Object(Slim\Http\Request))
#17 /opt/tacacsgui/web/api/vendor/tuupola/callable-handler/src/DoublePassTrait.php(47): Tuupola\Middleware\JwtAuthentication->process(Object(Slim\Http\Request), Object(Tuupola\Middleware\CallableHandler))
#18 [internal function]: Tuupola\Middleware\JwtAuthentication->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#19 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Tuupola\Middleware\JwtAuthentication), Array)
#20 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#21 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#22 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#23 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#24 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#25 /opt/tacacsgui/web/api/index.php(5): Slim\App->run()
#26 {main}
Previous exception
Type: Doctrine\DBAL\Driver\PDO\Exception
Code: 1045
Message: SQLSTATE[HY000] [1045] Access denied for user 'tgui_user'@'localhost' (using password: YES)
File: /opt/tacacsgui/web/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php
Line: 18
Trace
#0 /opt/tacacsgui/web/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(44): Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
#1 /opt/tacacsgui/web/api/vendor/illuminate/database/Connectors/Connector.php(67): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'tgui_user', 'RVoA}uL`EdPjDMq...', Array)
#2 /opt/tacacsgui/web/api/vendor/illuminate/database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'tgui_user', 'RVoA}uL`EdPjDMq...', Array)
#3 /opt/tacacsgui/web/api/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#4 /opt/tacacsgui/web/api/vendor/illuminate/database/Connectors/ConnectionFactory.php(182): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#5 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#6 /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php(919): call_user_func(Object(Closure))
#7 /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php(944): Illuminate\Database\Connection->getPdo()
#8 /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php(399): Illuminate\Database\Connection->getReadPdo()
#9 /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php(325): Illuminate\Database\Connection->getPdoForSelect(true)
#10 /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from i...', Array)
#11 /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#12 /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php(333): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#13 /opt/tacacsgui/web/api/vendor/illuminate/database/Schema/MySqlBuilder.php(18): Illuminate\Database\Connection->select('select * from i...', Array)
#14 /opt/tacacsgui/web/api/app/Controllers/Auth/AuthController.php(26): Illuminate\Database\Schema\MySqlBuilder->hasTable('mavis_local')
#15 [internal function]: tgui\Controllers\Auth\AuthController->getSignIn(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#16 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#17 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#18 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#20 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#21 /opt/tacacsgui/web/api/app/Middleware/ChangeHeaderMiddleware.php(14): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#22 [internal function]: tgui\Middleware\ChangeHeaderMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#23 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(tgui\Middleware\ChangeHeaderMiddleware), Array)
#24 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#25 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#26 /opt/tacacsgui/web/api/vendor/tuupola/callable-handler/src/CallableHandler.php(51): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#27 /opt/tacacsgui/web/api/vendor/tuupola/slim-jwt-auth/src/JwtAuthentication.php(161): Tuupola\Middleware\CallableHandler->handle(Object(Slim\Http\Request))
#28 /opt/tacacsgui/web/api/vendor/tuupola/callable-handler/src/DoublePassTrait.php(47): Tuupola\Middleware\JwtAuthentication->process(Object(Slim\Http\Request), Object(Tuupola\Middleware\CallableHandler))
#29 [internal function]: Tuupola\Middleware\JwtAuthentication->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#30 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Tuupola\Middleware\JwtAuthentication), Array)
#31 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#32 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#33 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#34 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#35 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#36 /opt/tacacsgui/web/api/index.php(5): Slim\App->run()
#37 {main}
Previous exception
Type: PDOException
Code: 1045
Message: SQLSTATE[HY000] [1045] Access denied for user 'tgui_user'@'localhost' (using password: YES)
File: /opt/tacacsgui/web/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php
Line: 40
Trace
#0 /opt/tacacsgui/web/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(40): PDO->__construct('mysql:host=loca...', 'tgui_user', 'RVoA}uL`EdPjDMq...', Array)
#1 /opt/tacacsgui/web/api/vendor/illuminate/database/Connectors/Connector.php(67): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'tgui_user', 'RVoA}uL`EdPjDMq...', Array)
#2 /opt/tacacsgui/web/api/vendor/illuminate/database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'tgui_user', 'RVoA}uL`EdPjDMq...', Array)
#3 /opt/tacacsgui/web/api/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#4 /opt/tacacsgui/web/api/vendor/illuminate/database/Connectors/ConnectionFactory.php(182): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#5 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#6 /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php(919): call_user_func(Object(Closure))
#7 /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php(944): Illuminate\Database\Connection->getPdo()
#8 /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php(399): Illuminate\Database\Connection->getReadPdo()
#9 /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php(325): Illuminate\Database\Connection->getPdoForSelect(true)
#10 /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from i...', Array)
#11 /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#12 /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php(333): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#13 /opt/tacacsgui/web/api/vendor/illuminate/database/Schema/MySqlBuilder.php(18): Illuminate\Database\Connection->select('select * from i...', Array)
#14 /opt/tacacsgui/web/api/app/Controllers/Auth/AuthController.php(26): Illuminate\Database\Schema\MySqlBuilder->hasTable('mavis_local')
#15 [internal function]: tgui\Controllers\Auth\AuthController->getSignIn(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#16 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#17 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#18 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#20 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#21 /opt/tacacsgui/web/api/app/Middleware/ChangeHeaderMiddleware.php(14): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#22 [internal function]: tgui\Middleware\ChangeHeaderMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#23 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(tgui\Middleware\ChangeHeaderMiddleware), Array)
#24 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#25 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#26 /opt/tacacsgui/web/api/vendor/tuupola/callable-handler/src/CallableHandler.php(51): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#27 /opt/tacacsgui/web/api/vendor/tuupola/slim-jwt-auth/src/JwtAuthentication.php(161): Tuupola\Middleware\CallableHandler->handle(Object(Slim\Http\Request))
#28 /opt/tacacsgui/web/api/vendor/tuupola/callable-handler/src/DoublePassTrait.php(47): Tuupola\Middleware\JwtAuthentication->process(Object(Slim\Http\Request), Object(Tuupola\Middleware\CallableHandler))
#29 [internal function]: Tuupola\Middleware\JwtAuthentication->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#30 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Tuupola\Middleware\JwtAuthentication), Array)
#31 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#32 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#33 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#34 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#35 /opt/tacacsgui/web/api/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#36 /opt/tacacsgui/web/api/index.php(5): Slim\App->run()
#37 {main}

**Comment by anp135** [comment]
Which version tacgui did you tried?

Master unstable, ova image has e2234caebedcc4372aa9b5d0e61660566982315c

You can get works debian 12 with that commit...
